// Generated by scripts/verify_pytorch.py; fixed deterministic float64 parity benchmark.
export const PYTORCH_PARITY = {
  "framework": "PyTorch 2.13.0+cpu",
  "dtype": "float64",
  "max_abs_difference": 5.551115123125783e-17,
  "differences": {
    "output": 1.3877787807814457e-17,
    "loss": 0.0,
    "grad_input": 0.0,
    "grad_weight1": 2.7755575615628914e-17,
    "grad_bias1": 5.551115123125783e-17,
    "grad_weight2": 2.0816681711721685e-17,
    "grad_bias2": 5.551115123125783e-17
  },
  "status": "pass"
} as const;
