"""Compare a fixed custom-autograd forward/backward pass against CPU PyTorch in float64."""
from __future__ import annotations

import json
from pathlib import Path

import torch

ROOT = Path(__file__).resolve().parents[1]
payload = json.loads((ROOT / "verification" / "engine-parity.json").read_text())
dtype = torch.float64

def parameter(name: str, shape: tuple[int, ...]) -> torch.Tensor:
    return torch.tensor(payload[name], dtype=dtype).reshape(shape).requires_grad_(True)

input_tensor = parameter("input", (2, 2))
weight1 = parameter("weight1", (2, 3))
bias1 = parameter("bias1", (3,))
weight2 = parameter("weight2", (3, 2))
bias2 = parameter("bias2", (2,))
target = torch.tensor(payload["target"], dtype=dtype).reshape(2, 2)
logits = torch.tanh(input_tensor @ weight1 + bias1) @ weight2 + bias2
loss = -(torch.softmax(logits, dim=1).log() * target).sum() / 2
loss.backward()

torch_values = {"output": logits.detach().flatten().tolist(), "loss": loss.item(), "gradients": {"input": input_tensor.grad.flatten().tolist(), "weight1": weight1.grad.flatten().tolist(), "bias1": bias1.grad.flatten().tolist(), "weight2": weight2.grad.flatten().tolist(), "bias2": bias2.grad.flatten().tolist()}}
differences = {"output": max(abs(a - b) for a, b in zip(payload["output"], torch_values["output"])), "loss": abs(payload["loss"] - torch_values["loss"])}
for name, gradients in payload["gradients"].items():
    differences[f"grad_{name}"] = max(abs(a - b) for a, b in zip(gradients, torch_values["gradients"][name]))
max_difference = max(differences.values())
result = {"framework": f"PyTorch {torch.__version__}", "dtype": "float64", "max_abs_difference": max_difference, "differences": differences, "status": "pass" if max_difference < 1e-10 else "fail"}
(ROOT / "verification" / "pytorch-parity.json").write_text(json.dumps(result, indent=2))
(ROOT / "client" / "src" / "engine" / "pytorchParity.ts").write_text(
    "// Generated by scripts/verify_pytorch.py; fixed deterministic float64 parity benchmark.\n"
    f"export const PYTORCH_PARITY = {json.dumps(result, indent=2)} as const;\n"
)
print(json.dumps(result, indent=2))
